<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0</TargetFrameworks>
    <Version>3.7.4</Version>
    <Copyright>Copyright © Maurits Elbers (@MagicMau) 2015-2021. Elite: Dangerous and related material is © Frontier Developments plc</Copyright>
    <Company>MagicMau</Company>
    <PackageId>EliteJournalReader</PackageId>
    <AssemblyVersion>3.7.3.1</AssemblyVersion>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Authors>MagicMau</Authors>
    <OutputType>Library</OutputType>
    <Configurations>Debug;Release</Configurations>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
</Project>
